pipelines:
  branches:
    master:
      - step:
          name: Build and push to registry
          services:
            - docker
          script:
            - curl -O https://raw.githubusercontent.com/Tomas-Sereikis/bitbucket-gcloud-kubernetes-deployment/master/runner.sh && chmod +x runner.sh
            - . ./runner.sh; install_gcloud_sdk
            - . ./runner.sh; build_and_push_docker_container
      - step:
          name: Deploy to production
          trigger: manual
          deployment: production
          services:
            - docker
          script:
            - curl -O https://raw.githubusercontent.com/Tomas-Sereikis/bitbucket-gcloud-kubernetes-deployment/master/runner.sh && chmod +x runner.sh
            - . ./runner.sh; install_gcloud_sdk
            - . ./runner.sh; kubectl_deploy $GCLOUD_CLUSTER_PRODUCTION
